version: "3.9"
services:
  frontend:
    build:
        dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
  server:
    build:
        dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
